### ISSUE TITLE
documentation inaccurate for restarting/logging website

### ISSUE THREAD

**Issue by amdugas** [scizen9/sedmpy#17]
The [document](https://v1.overleaf.com/17736887dnmzjnnskhgs#/67262640/) is out of date and the log file specified in /tmp/supervisord.conf (/tmp/supervisord.log) is not receiving new output.

The master branch in /scr2/sedm/sedmpy/ doesn't have my recent commits for visibility, but somehow pharos.caltech.edu/visibility is (sporadically, but without a log I can't see why) working. Where are we running the website from, if not this directory?

I can also update the documentation myself if anyone can tell me the information.

**Comment by rswalters** [comment]
Here is the procedure for starting things up. 

1. Start-up procedure.  Supervisord is still run with python2 put needs to point to the new config file

/usr/local/anaconda2/bin/python /usr/local/anaconda2/bin/supervisord -c /scr2/sedm/supervisord.conf.py3_6

2. The gunicorn startup now needs to point to the custom python3 version and needs to be started in the /scr2/sedm/sedm-site-py3 directory

/scr2/sedm/anaconda3/bin/python /scr2/sedm/anaconda3/bin/gunicorn -w 4 sedm_flask:app

I have been killing things manually because the last time I tried restarting via HUP it didn't show their updates.
